### ISSUE TITLE
ping läuft im Entwurfsmodus weiter

### ISSUE THREAD

**Issue by pyropeter** [pyropeter/filius#16]
...und macht dann komisches Zeuchs, wenn man wieder in den Simulationsmodus wechselt.

**Comment by kpj** [comment]
Wird Objekt des gerade benutzten Terminals nich garbage-collected, wenn man es schließt ?!

Am 29.01.2012 um 02:27 schrieb pyropeterreply@reply.github.com:

**Comment by pyropeter** [comment]
Ne, die Objekte bleiben alle erhalten.
Einige werden per beenden() und starten() de- bzw. aktiviert, wenn man zwischen Entwicklungs- und Simulationsmodus wechselt.
