### ISSUE TITLE
traceroute ist undokumentiert

### ISSUE THREAD

**Issue by pyropeter** [pyropeter/filius#7]
Hinweise fehlen an folgenden Stellen:
- HTML-Handbuch
- `help` im Terminal

**Comment by pyropeter** [comment]
(Das HTML-Handbuch deckt das Terminal nicht ab, daher wurde dort nichts geändert)

**Comment by kpj** [comment]
fix #7: Nun nicht mehr

**Comment by pyropeter** [comment]
Ich bin mir nicht ganz sicher, was dein commit bezweckte.
Ich habe den mal revertiert: c4180239ad4913beab16f18597d52eb6d7b794fb

**Comment by kpj** [comment]
?! Die hilf ewird beim start nicht mehr angezeigt ?!

Am 29.01.2012 um 14:58 schrieb pyropeterreply@reply.github.com:

**Comment by pyropeter** [comment]
Sollte sie aber.

**Comment by kpj** [comment]
Dann war dein bugreport missverständlich ;)

Am 29.01.2012 um 15:41 schrieb pyropeterreply@reply.github.com:
