### ISSUE TITLE
Terminal verstehen und ggf. neuschreiben

### ISSUE THREAD

**Issue by pyropeter** [pyropeter/filius#8]
Einige Ideen:
- Prompt und Befehlsfunktionen sollten synchron im gleichen Thread laufen
- `benachrichtigeBeobachter` sollte durch eine mehrmals aufrufbare Funktion ersetzt werden
- `benachrichtigeBeobachter` sollte `print` heißen
- Signale sollten das Abbrechen von Befehlen erlauben. Der Einfachheit halber könnte man einfach einen interrupt-Flag setzen, den der Befehl dann zu einem passenden Zeitpunkt abfragen kann (ping z.B. könnte nach jedem Paket ggf. Abbrechen)

Die durchführbaren Änderungen sollten in Form eines neuen Bugreports bearbeitet werden.

**Comment by kpj** [comment]
Mission accomplished!

**Comment by pyropeter** [comment]
Dieser Bug wurde ersetzt durch #15, #11 und #4
